// react/src/pages/pmi/pmi.js
import React from 'react';
import './pmi.scss';
import PmiDetailTemplate from './detail/pmiDetail.js';
import 'devextreme/data/odata/store';
import CustomStore from 'devextreme/data/custom_store';
import 'devextreme-react/text-area';
import DataGrid, {
  Column,
  Pager,
  Paging,
  Sorting,
  FilterRow,
  MasterDetail
} from 'devextreme-react/data-grid';



class PmiComponent extends React.Component {
  constructor() {
    super();
    this.state = {
      baseCurrency: null,
      quoteCurrency: null,
      occurencesCount: null,
      exchange: null
    };
    this.baseCurrencyChange = this.baseCurrencyChange.bind(this);
    this.occurencesCountChange = this.occurencesCountChange.bind(this);
    this.quoteCurrencyChange = this.quoteCurrencyChange.bind(this);
    this.exchangeChange = this.exchangeChange.bind(this);
  }

  exchangeChange(event) {
    this.setState({exchange: event.target.value});
  }

  baseCurrencyChange(event) {
    this.setState({baseCurrency: event.target.value});
  }

  occurencesCountChange(event) {
    this.setState({occurencesCount: event.target.value});
  }
  
  quoteCurrencyChange(event) {
    this.setState({quoteCurrency: event.target.value});
  }


  render() {

    return (

    <React.Fragment>
      <div class="input-block wrap">
        <label for="baseCurrency">BaseCurrency:</label>
        <input type="text" id="baseCurrency" value={this.state.baseCurrency} onChange={this.baseCurrencyChange} />
      </div>
      <div class="input-block">
        <label for="baseCurrency">QuoteCurrency:</label>
        <input type="text" id="baseCurrency" value={this.state.quoteCurrency} onChange={this.quoteCurrencyChange} />
      </div>
      <div class="input-block">
        <label for="baseCurrency">OccurencesCount:</label>
        <input type="text" id="baseCurrency" value={this.state.occurencesCount} onChange={this.occurencesCountChange} />
      </div>
      <div class="input-block">
      <label for="exchange">Exchange:</label>
      <input type="text" id="exchange" value={this.state.exchange} onChange={this.exchangeChange} />
      </div>

      <DataGrid
      className={'dx-card wide-card'}
      dataSource={gridSource(this.state)}
      ref={(ref) => this.dataGrid = ref}
      selection={{ mode: 'single' }}
      showBorders={false}
      focusedRowEnabled={true}
      defaultFocusedRowIndex={0}
      columnAutoWidth={true}
      columnHidingEnabled={true}
      remoteOperations={true}
  
    >
      <Paging defaultPageSize={5} />
      <Sorting mode="none" />
      <Pager showPageSizeSelector={true}
             allowedPageSizes={[5]}
             showInfo={true} />
      <FilterRow visible={false} />
      <Column dataField={'unificatedPairName'} hidingPriority={1} />
      <Column dataField={'baseCurrency'} hidingPriority={3} />
      <Column dataField={'quoteCurrency'}  hidingPriority={4} />
      <Column dataField={'occurrencesCount'}  hidingPriority={2} />
      <MasterDetail
      enabled={true}
      component={PmiDetailTemplate}
    />
      
    </DataGrid>
   
      </React.Fragment>
    );
  }
}

export default PmiComponent

function isNotEmpty(value) {
  return value !== undefined && value !== null && value !== '';
}

function gridSource(objectState) {
  return new CustomStore({
    key: 'unificatedPairName',
    load: function(loadOptions) {
      let params = '?';
      let count = 5;
      let offset = loadOptions.skip;
  
      params += `${'count'}=${JSON.stringify(count)}&`; 
      params += `${'offset'}=${JSON.stringify(offset)}&`; 
  
      if(!!objectState.baseCurrency){
        params += `${'baseCurrency'}=${objectState.baseCurrency}&`; 
      }
      if(!!objectState.quoteCurrency){
        params += `${'quoteCurrency'}=${objectState.quoteCurrency}&`; 
      }
      if(!!objectState.occurencesCount){
        params += `${'ListedMoreThan'}=${objectState.occurencesCount}&`; 
      }
      if(!!objectState.exchange){
        params += `${'exchange'}=${objectState.exchange}&`; 
      }
      params = params.slice(0, -1);
      return fetch(`http://localhost:6000/api/v1/pair-info/unique${params}`)
        .then(response => response.json())
        .then((data) => {
          return {
            data: data.items,
            totalCount: data.total,
            summary: data.total,
            groupCount: data.total
          };
        })
        .catch(() => { throw 'Data Loading Error'; });
    }
  });;
}

// angular/arbital-system/src/app/pages/pmi/pmi.component.ts
import { HttpClient, HttpParams } from '@angular/common/http';
import { parseI18nMeta } from '@angular/compiler/src/render3/view/i18n/meta';
import { Component, Inject, ViewChild } from '@angular/core';
import { DxDataGridComponent } from 'devextreme-angular';
import DataSource from 'devextreme/data/data_source';
import { Observable } from 'rxjs';
import { AppInfoService } from 'src/app/shared/services';
import { AppDataService } from 'src/app/shared/services/app-data.service';
import { IApiLookupNameDto } from 'src/app/shared/services/model/IApiLookupNameDto';
import { environment } from 'src/environments/environment';

@Component({
  templateUrl: 'pmi.component.html',
  styleUrls: ['./pmi.component.scss']
})

export class PmiComponent {
  dataSource: any;
  baseCurrency: string;
  quoteCurrency: string;
  occurencesCount: string;
  exchange: IApiLookupNameDto;
  exchangeData: IApiLookupNameDto[];
  exchangeGrid: string;
  gridDataSource: any = {};
  @ViewChild('dataGridVar', { static: false }) dataGrid: DxDataGridComponent;
  @ViewChild('dataExchangeGridVar', { static: false }) dataExchangeGrid: DxDataGridComponent;

  constructor(public appData: AppDataService, @Inject(HttpClient) httpClient: HttpClient, public appInfoData: AppInfoService) {
    
  appInfoData.loadExchangeLookupData('')
    .toPromise()
          .then((result: any) => {
            this.exchangeData = result;
          });

    this.gridDataSource = new DataSource({
      key: "unificatedPairName",
      load: (loadOptions) => {
        let params: HttpParams = new HttpParams();
        [
          "skip",
          "take",
          "count"
        ].forEach(function (i) {
          if (i in loadOptions && isNotEmpty(loadOptions[i]))
            if (i === 'skip') {
              params = params.set('offset', JSON.stringify(loadOptions[i]));
            }
            else {
              params = params.set(i, JSON.stringify(loadOptions[i]));
            }
        });
        params = params.set("count", this.gridDataSource._pageSize);
        params = this.setCustomParameters(params);
        return httpClient.get(arbitaPairInfolUrl(), { params: params })
          .toPromise()
          .then((result: any) => {
            return {
              data: result.items,
              totalCount: result.total,
              summary: result.total,
              groupCount: result.total
            };
          });
      }
    });


    function isNotEmpty(value: any): boolean {
      return value !== undefined && value !== null && value !== "";
    }

    function arbitaPairInfolUrl() {
      return environment.apiUrl + `/api/v1/pair-info/unique`;
    }
    function arbitaPairInfoExchangelUrl(exchange) {
      if (exchange) {
        return environment.apiUrl + `/api/v1/pair-info/${exchange}`;
      }
      return environment.apiUrl + `/api/v1/pair-info`;
    }
  }

  setCustomParameters(params){

    if (!!this.baseCurrency) {
      params = params.set("baseCurrency", this.baseCurrency);
    }
    if (!!this.occurencesCount) {
      params = params.set("occurencesCount", this.occurencesCount);
    }
    if (!!this.quoteCurrency) {
      params = params.set("quoteCurrency", this.quoteCurrency);
    }
    if (!!this.exchange) {
      params = params.set("exchange", this.exchange);
    }
    return params;
  }

  gridRefresh() {
    this.dataGrid.instance.refresh();
  }

  gridExchangeRefresh() {
    this.dataExchangeGrid.instance.refresh();
  }

}

<h2 class="content-block">Pair Information</h2>
<div class="dx-fieldset">

  <div class="row">
    <div class="col-2">
      <div class="dx-field">
        <div class="dx-field-label">
          BaseCurrency
          <dx-text-box [(value)]="baseCurrency"></dx-text-box>
        </div>
      </div>
    </div>
    <div class="col-2">
      <div class="dx-field">
        <div class="dx-field-label">
          QuoteCurrency
          <dx-text-box [(value)]="quoteCurrency"></dx-text-box>
        </div>
      </div>
    </div>
    <div class="col-2">
      <div class="dx-field">
        <div class="dx-field-label">
          OccurencesCount
          <dx-text-box [(value)]="occurencesCount"></dx-text-box>
        </div>
      </div>
    </div>
    <div class="col-2">
      <div class="dx-field">
        <div class="dx-field-label">
          Exchange
          <dx-select-box [items]="exchangeData" [(value)]="exchange" displayExpr="name" showClearButton="true"
            valueExpr="id"></dx-select-box>
        </div>
      </div>
    </div>
    <div class="col-3">

    </div>
    <div class="col-1">
      <dx-button stylingMode="contained" text="Search" type="normal" [width]="120" (onClick)="gridRefresh()">
      </dx-button>
    </div>
  </div>
</div>

<dx-data-grid #dataGridVar id="gridContainer" [dataSource]="gridDataSource" [showBorders]="true"
  [remoteOperations]="true">
  <dxo-header-filter [visible]="false"></dxo-header-filter>
  <dxo-sorting mode="none"></dxo-sorting>
  <dxo-paging [pageSize]="10"></dxo-paging>
  <dxo-pager [showPageSizeSelector]="true" [allowedPageSizes]="[10, 25, 50, 100]"></dxo-pager>

  <dxo-master-detail [enabled]="true" template="detail"></dxo-master-detail>
  <div *dxTemplate="let dt of 'detail'">
    <div class="master-detail-caption">Detail</div>
    <pmi-detail-grid [key]="dt.key"></pmi-detail-grid>
  </div>
</dx-data-grid>
